# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Australia and Aotearoa NZ Public History Network
subtitle: AAPHN
logo: /assets/images/Buecher-lineart.png
email:
description: >- # this means to ignore newlines until "baseurl:"
 The Australia and Aotearoa NZ Public History Network aims to to develop public history across Australasia by creating opportunities to communicate, meet and share knowledge among individuals and organisations who practice public and applied history in the academy, communities, industry and professions.
twitter_username: "AppliedHist"
minimal_mistakes_skin: contrast
search: true
og_image: /assets/images/old_photos_2_small.jpg

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Sydney


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "AAPHN"
  avatar : "/assets/images/old_photos_square.jpg"
  bio    : "A network for public historians and enthusiasts across Australasia to connect, communicate and collaborate. Join the network by contacting us at <aaphn@mq.edu.au> or sign up to our newsletter below."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/aaphnetwork"
    - label: "Newsletter"
      icon: "fas fa-newspaper"
      url: "http://eepurl.com/hRFpxv"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mq-cah"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/aaphnetwork"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mq-cah"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

teaser: /assets/images/old_photos_2_banner.jpg
caption: "© State Library of NSW. Photo by Joy Lai"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
